---

- name: Build model '{{ amp_entities[step.entity_label]['create_model']['name'] }}'
  tags: model
  block:
    - name: Attempt to build the model
      cloudera.runtime.ml_project_model_build:
        endpoint: "{{ amp_endpoint }}"
        api_key: "{{ amp_api_key }}"
        project_id: "{{ __amp_project.project.id }}"
        model_id: "{{ amp_entities[step.entity_label]['create_model']['id'] }}"
        comment: "{{ step.comment | default(omit) }}"
        file: "{{ step.target_file_path }}"
        function: "{{ step.target_function_name }}"
        runtime: "{{ __amp_runtime_image_identifier }}"
      register: __step

    - name: Register model '{{ step.name }}' entity
      ansible.builtin.set_fact:
        amp_entities: "{{ amp_entities | combine({ step.entity_label : entity_steps }) }}"
      vars:
        entity_steps: "{{ amp_entities[step.entity_label] | default({}) | combine({ step.type : entity })}}"
        entity:
          id: "{{ __step.build.id }}"
  rescue:
    - name: Monitor status of the model build
      retries: 60
      delay: 10
      until: __step_monitor.model_builds[0].status == 'built'
      cloudera.runtime.ml_project_model_build_info:
        endpoint: "{{ amp_endpoint }}"
        api_key: "{{ amp_api_key }}"
        project_id: "{{ __amp_project.project.id }}"
        model_id: "{{ amp_entities[step.entity_label]['create_model']['id'] }}"
      register: __step_monitor

    - name: Register model '{{ step.name }}' entity
      ansible.builtin.set_fact:
        amp_entities: "{{ amp_entities | combine({ step.entity_label : entity_steps }) }}"
      vars:
        entity_steps: "{{ amp_entities[step.entity_label] | default({}) | combine({ step.type : entity })}}"
        entity:
          id: "{{ __step_monitor.model_builds[0].id }}"

- name: Monitor status of the model build
  retries: 60
  delay: 10
  until: __step_monitor.model_builds[0].status == 'built'
  cloudera.runtime.ml_project_model_build_info:
    endpoint: "{{ amp_endpoint }}"
    api_key: "{{ amp_api_key }}"
    project_id: "{{ __amp_project.project.id }}"
    model_id: "{{ amp_entities[step.entity_label]['create_model']['id'] }}"
  register: __step_monitor