---

- name: Create model '{{ step.name }}'
  tags: ['model', 'application']
  cloudera.runtime.ml_project_model:
    endpoint: "{{ amp_endpoint }}"
    api_key: "{{ amp_api_key }}"
    project_id: "{{ __amp_project.project.id }}"
    name: "{{ step.name }}"
    desc: "{{ step.description }}"
    auth: False
  register: __step

- name: Register model '{{ step.name }}' entity
  tags: ['model', 'application']
  ansible.builtin.set_fact:
    amp_entities: "{{ amp_entities | combine({ step.entity_label : entity_steps }) }}"
  vars:
    entity_steps: "{{ amp_entities[step.entity_label] | default({}) | combine({ step.type : entity })}}"
    entity:
      id: "{{ __step.model.id }}"
      name: "{{ __step.model.name }}"
      access_key: "{{ __step.model.access_key | default(omit) }}"

- name: Update the AMP model access key on the project
  tags: ['model', 'application']
  when: step.access_key_environment_variable
  cloudera.runtime.ml_project:
    endpoint: "{{ amp_endpoint }}"
    api_key: "{{ amp_api_key }}"
    id: "{{ __amp_project.project.id }}"
    env: "{{ __amp_project.project.environment | from_json | combine({ step.access_key_environment_variable : __step.model.access_key }) }}"
