---

- name: Create job '{{ step.name }}'
  tags: jobs
  cloudera.runtime.ml_project_job:
    endpoint: "{{ amp_endpoint }}"
    api_key: "{{ amp_api_key }}"
    project_id: "{{ __amp_project.project.id }}"
    name: "{{ step.name }}"
    script: "{{ step.script }}"
    arguments: "{{ step.arguments | bool | ternary(step.arguments, omit) | default(omit) }}"
    env: "{{ step.environment | default(omit) }}"
    runtime: "{{ __amp_runtime_image_identifier }}"
  register: __step

- name: Register job '{{ step.name }}' entity
  tags: jobs
  ansible.builtin.set_fact:
    amp_entities: "{{ amp_entities | combine({ step.entity_label : entity_steps }) }}"
  vars:
    entity_steps: "{{ amp_entities[step.entity_label] | default({}) | combine({ step.type : entity })}}"
    entity:
      id: "{{ __step.job.id }}"
      name: "{{ __step.job.name }}"
