---

- name: Deploy model '{{ amp_entities[step.entity_label]['create_model']['name'] }}'
  tags: model
  cloudera.runtime.ml_project_model_deployment:
    endpoint: "{{ amp_endpoint }}"
    api_key: "{{ amp_api_key }}"
    project_id: "{{ __amp_project.project.id }}"
    model_id: "{{ amp_entities[step.entity_label]['create_model']['id'] }}"
    cpu: "{{ step.cpu | default(omit) }}"
    gpu: "{{ step.gpu | default(omit) }}"
    memory: "{{ step.memory | default(omit) }}"
    env: "{{ step.environment_variables | default(omit) }}"
  register: __step

- name: Register model '{{ step.name }}' entity
  tags: model
  ansible.builtin.set_fact:
    amp_entities: "{{ amp_entities | combine({ step.entity_label : entity_steps }) }}"
  vars:
    entity_steps: "{{ amp_entities[step.entity_label] | default({}) | combine({ step.type : entity })}}"
    entity:
      id: "{{ __step.deployment.id }}"