---

- name: Modify job '{{ amp_entities[step.entity_label]['create_job']['name'] }}'
  tags: jobs
  when: step.cpu or step.gpu or step.memory
  cloudera.runtime.ml_project_job:
    endpoint: "{{ amp_endpoint }}"
    api_key: "{{ amp_api_key }}"
    project_id: "{{ __amp_project.project.id }}"
    id: "{{ amp_entities[step.entity_label]['create_job']['id'] }}"
    cpu: "{{ step.cpu | default(omit) }}"
    gpu: "{{ step.gpu | default(omit) }}"
    memory: "{{ step.memory | default(omit) }}"

- name: Run job '{{ amp_entities[step.entity_label]['create_job']['name'] }}'
  tags: jobs
  cloudera.runtime.ml_project_job_run:
    endpoint: "{{ amp_endpoint }}"
    api_key: "{{ amp_api_key }}"
    project_id: "{{ __amp_project.project.id }}"
    id: "{{ amp_entities[step.entity_label]['create_job']['id'] }}"
    arguments: "{{ step.arguments | default(False) | bool | ternary(step.arguments, omit) }}"
    env: "{{ step.environment | default(omit) }}"
    wait: yes