---

- name: Start application '{{ step.name }}'
  tags: application
  cloudera.runtime.ml_project_application:
    endpoint: "{{ amp_endpoint }}"
    api_key: "{{ amp_api_key }}"
    project_id: "{{ __amp_project.project.id }}"
    name: "{{ step.name }}"
    auth: True
    script: "{{ step.script }}"
    subdomain: "{{ step.subdomain }}"
    env: "{{ step.environment_variables | default(omit) }}"
    runtime: "{{ __amp_runtime_image_identifier }}"
    state: restarted
  register: __step
